### ISSUE TITLE
There was an error when I tried new Pathfinding

### ISSUE THREAD

**Issue by jackwellgithub** [neki-dev/pathfinding-worker#2]
When I imported the pathfinding work package and executed this line of code
const pathfinding = new Pathfinding({
loopRate: 500,
});

An error occurred:
_**index.js:1  Uncaught TypeError: n2.Worker is not a constructor
at new y (index.js:1:26235)
at main.ts:4:21**_

Excuse me, is there a problem with my usage?

**Comment by neki-dev** [comment]
Are you using this library in node.js platform? 
That looks like you tried to use this library in browser

**Comment by jackwellgithub** [comment]
Thank you very much. When I used the libraries in the Node.js server, it ran successfully.
